export default {
  url: "https://www.securian.com/insights-tools/retirement-calculator.html",
  "Current Age": 40,
  "Retirement Age": 68,
  "Current annual income": "$100000",
  "Spouse’s annual income": "$75000",
  "Current retirement savings": "$500000",
  "Current retirement contribution": 10,
  "Annual retirement contribution increase": 5,
  "Social Security Income": "Yes",
  "Relationship status": "Married",
  "Social Security Override": "$4000",
  "Additional/other income": 500,
  "Number of years retirement needs to last": 20,
  "Post-retirement income increase with inflation": "Yes",
  "Inflation rate": 5,
  "Percent of final annual income desired": 75,
  "Pre-retirement investment return": 8,
  "Post-retirement investment return": 5,
};
